# Travis Continuous Integration Configuration File, based on ..
#   Generic MoveIt Travis Continuous Integration Configuration File
#   Works with all MoveIt! repositories/branches
#   Author: Dave Coleman, Jonathan Bohren
language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
env:
  matrix:
    - ROS_DISTRO=groovy USE_DEB=true
    - ROS_DISTRO=groovy USE_DEB=false
    - ROS_DISTRO=hydro  USE_DEB=true
    - ROS_DISTRO=hydro  USE_DEB=false
notifications:
  email:
    recipients:
      - k-okada@jsk.t.u-tokyo.ac.jp
    on_success: always #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-ros
  # Setup rosdep
  - sudo rosdep init
  - rosdep update
install: # Use this to install any prerequisites or dependencies necessary to run your build
  # Create workspace
  - mkdir -p ~/ros/ws_$REPOSITORY_NAME/src
  - cd ~/ros/ws_$REPOSITORY_NAME/src
  - if [ $USE_DEB == "true" ] ; then ln -s $CI_SOURCE_PATH . ; fi # Link the repo we are testing to the new workspace
  - if [ $USE_DEB == "false" ] ; then wstool init .; wstool merge http://raw.github.com/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/.rosinstall ; wstool update; fi # install everything from source
  - cd ../
  # Install dependencies for source repos
  - rosdep install -r -n --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y
before_script: # Use this to prepare your build for testing e.g. copy database configurations, environment variables, etc.
  - source /opt/ros/$ROS_DISTRO/setup.bash
script: # All commands must exit with code 0 on success. Anything else is considered failure.
  - find . \! -path "*/.*" -type f | xargs egrep -i "(hoge|fuga)" ; if [ $? == 0 ]; then exit 1; fi
  - catkin_make
  - catkin_make test
  - catkin_make install
  - rm -fr devel src build
  - source install/setup.bash
  - find install -iname "*.test" -print0 | xargs -0 -n1 rostest
after_failure:
  - cat ./build/Testing/Temporary/LastTest.log


